"swap" new fs type added

diff --git a/fsLuks b/fsLuks
--- a/fsLuks
+++ b/fsLuks
@@ -5,8 +5,8 @@
 # location: http://www.dvgu.ru/forum/thread.php?threadid=1518&page=2#post43879
 # license: GNU GPL
 # author: webadm at dvgu dot ru
-# version: 1.0.8
-# date: 2007-09-08
+# version: 1.0.9
+# date: 2008-01-11
 
 # config
 ADJUST_2_NERO=307200				# will Nero burner be used? yes=307200, no=0
@@ -17,19 +17,21 @@ A_ISO_MEDIA_SIZE=($((737280000-$ADJUST_2_NERO)) $((4700372992-$ADJUST_2_NERO)) $
 						# - http://www.osta.org/technology/cdqa7.htm
 						# - http://www.osta.org/technology/dvdqa/dvdqa6.htm
 OPTS_CRYPTSETUP_FORMAT="--batch-mode -s 256"	# luksFormat options, default is "-c aes-cbc-essiv:sha256 -s 128"
-A_FS_TYPES=("iso9660" "ext3" "vfat")		# supported fstype names array
-A_OPTS_LOSETUP=("-r" "" "")			# fstype-specific losetup options, coherently to A_FS_TYPES
-A_OPTS_CRYPTSETUP_OPEN=("--readonly" "" "")	# fstype-specific luksOpen options, coherently to A_FS_TYPES
-A_OPTS_MKFS=(					# fstype-specific mkfs options, coherently to A_FS_TYPES
+A_FS_TYPES=("iso9660" "ext3" "vfat" "swap")	# supported fstype names array
+A_OPTS_LOSETUP=("-r" "" "" "")			# fstype-specific losetup options, coherently to A_FS_TYPES
+A_OPTS_CRYPTSETUP_OPEN=("--readonly" "" "" "")	# fstype-specific luksOpen options, coherently to A_FS_TYPES
+A_OPTS_MKFS=(					# fstype-specific mkfs/mkswap options, coherently to A_FS_TYPES
   "-quiet -allow-leading-dots -joliet-long -iso-level 3 -l -J -r"
   ""
   "-F 32"
+  "-c"
 )
-A_OPTS_FSCK=("" "" "-- -atvV")			# fstype-specific fsck options, coherently to A_FS_TYPES
-A_OPTS_MOUNT=(					# fstype-specific mount options, coherently to A_FS_TYPES
+A_OPTS_FSCK=("" "" "-- -atvV" "")		# fstype-specific fsck options (ignored for swap), coherently to A_FS_TYPES
+A_OPTS_MOUNT=(					# fstype-specific mount/swapon options, coherently to A_FS_TYPES
   "-o iocharset=utf8,noatime,nodev,noexec,nosuid,ro,unhide,utf8"
   "-o acl,user_xattr"
   "-o async,codepage=866,dmask=0022,fmask=0133,iocharset=utf8,nodev,noexec,nosuid,showexec,shortname=lower,utf8"
+  ""
 )
 
 # vars
@@ -53,7 +55,7 @@ Options and parameters:
     --print map, -p map
 	Print various meta information about LUKS partition assigned to /dev/mapper/map
     --close map, -c map
-	Umount /dev/mapper/map and close LUKS partition
+	Unmount /dev/mapper/map and close LUKS partition
     --data, -d
 	Some LUKS partition data parameters, action-dependent:
 	--data sdir ifile
@@ -69,24 +71,27 @@ Options and parameters:
 	--data ifile
 	    Open or print or close LUKS partition in ifile image file
     --mount mdir, -m mdir
-	Mount LUKS partition to mdir directory. Required for 'build' or 'open' action
+	Mount LUKS partition to mdir directory. Required for 'build' or 'open' action. For 'swap'
+	fstype is ignored and may be omited.
     --fstype fsname, -t fsname
 	Filesystem type name. Required for 'build' or 'open' action. May be one of: ${A_FS_TYPES[@]}
     --key kfile, -k kfile
-	Passphrase containing file. Required for 'build' or 'open' action. if not specified, passphrase will be asked
+	Passphrase containing file. Required for 'build' or 'open' action. If not specified, passphrase will be asked
 	
 Examples:
-    $SCRIPT_NAME --build cdrom --data /dir  iso.image  --mount /mnt --key secret.txt
+    $SCRIPT_NAME --build cdrom --data /dir  iso.image  --mount /mnt               --key secret.txt
     $SCRIPT_NAME --build encfs --data 1440k vfat.image --mount /mnt --fstype vfat
     $SCRIPT_NAME --build flash --data       /dev/sda1  --mount /mnt --fstype ext3
+    $SCRIPT_NAME --build swap  --data 512m  swap.image --mount none --fstype swap
     $SCRIPT_NAME --open  encfs --data       ext3.image --mount /mnt --fstype ext3
-    $SCRIPT_NAME --open  fd0   --data       /dev/fd0   --mount /mnt --fstype vfat" >&2
+    $SCRIPT_NAME --open  fd0   --data       /dev/fd0   --mount /mnt --fstype vfat
+    $SCRIPT_NAME --open  swap  --data       /dev/sda2  --mount none --fstype swap --key secret.txt" >&2
   exit 1
 }
 
 # output $1, release resources occupied, exit
 function Exit () {
-  echo "Failed$1" >&2;
+  echo "Failed$1" >&2
   if [ -n "$ACTION" ]; then
     LUKS_Close
     [ $ACTION -eq 0 -a -n "$FILE_IMAGE" ] && rm -f "$FILE_IMAGE"
@@ -122,7 +127,7 @@ function DevLoop_Init () {
   if [ -z "$DEV_LOOP" ]; then
     Notify "Look for free loop device: " -n
     for i in /dev/loop*; do
-      if ! losetup $i > /dev/null 2>&1; then DEV_LOOP=$i; break; fi
+      if ! losetup $i &> /dev/null; then DEV_LOOP=$i; break; fi
     done
     [ -n "$DEV_LOOP" ] && Notify "$DEV_LOOP" || Exit
   fi
@@ -169,10 +174,14 @@ function LUKS_Format_And_Open () {
   LUKS_Open $1 $2
 }
 
-# requires global vars: $FS_TYPE, $DEV_MAP, $DIR_MOUNT
+# requires global vars: $FS_TYPE, $DEV_MAP, $DIR_MOUNT (last for non-swap only)
 function LUKS_Mount () {
   Notify "Mount LUKS partition: " -n
-  mount -t ${A_FS_TYPES[$FS_TYPE]} ${A_OPTS_MOUNT[$FS_TYPE]} /dev/mapper/$DEV_MAP "$DIR_MOUNT" && Notify || Exit
+  if [ "$FS_TYPE" == "3" ]; then
+    swapon ${A_OPTS_MOUNT[$FS_TYPE]} /dev/mapper/$DEV_MAP && Notify || Exit
+  else
+    mount -t ${A_FS_TYPES[$FS_TYPE]} ${A_OPTS_MOUNT[$FS_TYPE]} /dev/mapper/$DEV_MAP "$DIR_MOUNT" && Notify || Exit
+  fi
 }
 
 # silently (since it may be called from Exit) release resources occupied; requires global var $ACTION
@@ -188,7 +197,6 @@ function LUKS_Close () {
 [ "$UID" == "0" ] || Exit ": this script must be run as root"
 (($# > 0)) || Explain_And_Exit
 if ! cryptsetup --help | grep -q luksFormat; then Exit ": LUKS support is required"; fi
-#TODO: check is swap being encrypted?
 
 # parse input params
 
@@ -247,7 +255,7 @@ done
 [[ -z "$FILE_SIZE" || "$FILE_SIZE" =~ "^[1-9][0-9]*$" && $FILE_SIZE -ge 1474560 ]] || Exit ": fsize $FILE_SIZE is invalid or too small"	#TODO: clarify min fs size for ext3, vfat
 [ -z "$DEV_DATA" -o -b "$DEV_DATA" ] || Exit ": device $DEV_DATA is invalid"
 [ -z "$DIR_IMAGE" -o -d "$DIR_IMAGE" ] || Exit ": dir $DIR_IMAGE is not found"
-[ -z "$DIR_MOUNT" -o -d "$DIR_MOUNT" ] || Exit ": dir $DIR_MOUNT is not found"
+[ -z "$DIR_MOUNT" -o -d "$DIR_MOUNT" -o "$FS_TYPE" == "3" ] || Exit ": dir $DIR_MOUNT is not found"
 [ -z "$FILE_KEY" -o -s "$FILE_KEY" ] || Exit ": keyfile is empty or not found"
 [ $ACTION -eq 0 -o -z "$DIR_IMAGE" -a -z "$FILE_SIZE" ] || Exit ": some of excessive options are specified: sdir, fsize"
 [ $ACTION -ne 0 -o "$FS_TYPE" == "0" -o -z "$FS_TYPE" -o -n "$FILE_SIZE" -a -n "$FILE_IMAGE" -a -z "$DEV_DATA" -o -z "$FILE_SIZE" -a -z "$FILE_IMAGE" -a -n "$DEV_DATA" ] || Exit ": fsize and dev options are incompatible"
@@ -259,7 +267,7 @@ done
 [ $ACTION -gt 1 -o -n "$FILE_IMAGE" -o -n "$DEV_DATA" ] || Exit ": neither ifile, nor dev option is specified"
 [ $ACTION -gt 1 -o -n "$FS_TYPE" ] || Exit ": fstype option is not specified"
 [ $ACTION -gt 1 -o ! -b "/dev/mapper/$DEV_MAP" ] || Exit ": map already exists"
-[ $ACTION -gt 1 -o -n "$DIR_MOUNT" ] || Exit ": mdir option is not specified"
+[ $ACTION -gt 1 -o -n "$DIR_MOUNT" -o "$FS_TYPE" == "3" ] || Exit ": mdir option is not specified"
 [ $ACTION -lt 2 -o -z "$FS_TYPE" ] || Exit ": excessive fstype option is specified"
 [ $ACTION -lt 2 -o -b "/dev/mapper/$DEV_MAP" ] || Exit ": map is not found"
 [ $ACTION -lt 2 -o -z "$FILE_IMAGE" -a -z "$DIR_IMAGE" -a -z "$FILE_SIZE" -a -z "$DEV_DATA" -a -z "$DIR_MOUNT" -a -z "$FILE_KEY" ] || Exit ": some of excessive options are specified: ifile, sdir, fsize, dev, mdir, keyfile"
@@ -311,7 +319,7 @@ if [ "$ACTION" == "0" -a "$FS_TYPE" == "0" ]; then
   LUKS_Open $DEV_LOOP ${A_OPTS_CRYPTSETUP_OPEN[$FS_TYPE]}
 
   Notify "Verify iso9660 fs in /dev/mapper/$DEV_MAP: " -n
-  isovfy ${A_OPTS_FSCK[$FS_TYPE]} /dev/mapper/$DEV_MAP > /dev/null 2>&1 && Notify || Exit
+  isovfy ${A_OPTS_FSCK[$FS_TYPE]} /dev/mapper/$DEV_MAP &> /dev/null && Notify || Exit
 
   LUKS_Mount
 
@@ -321,10 +329,12 @@ elif [ "$ACTION" == "0" -a "$FS_TYPE" != "0" ]; then
     LUKS_Allocate $FILE_SIZE ${A_OPTS_LOSETUP[$FS_TYPE]}
   else
     DEV_DATA_SS=$(blockdev --getss $DEV_DATA)
-    Notify "Try to make temp file: " -n
-    FILE_BADBLOCK_LIST=$(mktemp) && Notify || Exit
-    badblocks -b $DEV_DATA_SS -c 256 -s -t random -v -w $DEV_DATA > $FILE_BADBLOCK_LIST
-    [ -s "$FILE_BADBLOCK_LIST" ] && Notify "Warning: $(cat $FILE_BADBLOCK_LIST | wc -l) bad blocks found on $DEV_DATA" || rm -f $FILE_BADBLOCK_LIST && FILE_BADBLOCK_LIST=""
+    if (($FS_TYPE != 3)); then
+      Notify "Try to make temp file: " -n
+      FILE_BADBLOCK_LIST=$(mktemp) && Notify || Exit
+      badblocks -b $DEV_DATA_SS -c 256 -s -t random -v -w $DEV_DATA > $FILE_BADBLOCK_LIST
+      [ -s "$FILE_BADBLOCK_LIST" ] && Notify "Warning: $(cat $FILE_BADBLOCK_LIST | wc -l) bad blocks found on $DEV_DATA" || rm -f $FILE_BADBLOCK_LIST && FILE_BADBLOCK_LIST=""
+    fi
     Notify "Randomize LUKS header"
     dd if=/dev/urandom of=$DEV_DATA bs=$DEV_DATA_SS count=$((2056 * 512 / $DEV_DATA_SS)) 2> /dev/null
 	# 2056x512 is max LUKS header length, corresponding to 256-bit keys
@@ -335,12 +345,16 @@ elif [ "$ACTION" == "0" -a "$FS_TYPE" != "0" ]; then
   dd if=/dev/zero of=/dev/mapper/$DEV_MAP bs=4k 2> /dev/null; Notify
 
   Notify "Make ${A_FS_TYPES[$FS_TYPE]} filesystem: " -n
-  mkfs -t ${A_FS_TYPES[$FS_TYPE]} $OPTS_MKFS ${FILE_BADBLOCK_LIST:+ -l $FILE_BADBLOCK_LIST} /dev/mapper/$DEV_MAP && Notify || Exit
-  rm -f $FILE_BADBLOCK_LIST
+  if (($FS_TYPE == 3)); then
+    mkswap $OPTS_MKFS /dev/mapper/$DEV_MAP && Notify || Exit
+  else
+    mkfs -t ${A_FS_TYPES[$FS_TYPE]} $OPTS_MKFS ${FILE_BADBLOCK_LIST:+ -l $FILE_BADBLOCK_LIST} /dev/mapper/$DEV_MAP && Notify || Exit
+    [ -n "$FILE_BADBLOCK_LIST" ] && rm -f $FILE_BADBLOCK_LIST
+  fi
 
   (($FS_TYPE == 1)) && { Notify "Tune filesystem: " -n; tune2fs -m 0 /dev/mapper/$DEV_MAP && Notify || Exit; }
 
-  (($FS_TYPE != 2)) && { Notify "Check filesystem: " -n; fsck -t ${A_FS_TYPES[$FS_TYPE]} /dev/mapper/$DEV_MAP ${A_OPTS_FSCK[$FS_TYPE]} && Notify || Exit; }	#FIXME: dosfsck fails on map
+  (($FS_TYPE != 2 && $FS_TYPE != 3)) && { Notify "Check filesystem: " -n; fsck -t ${A_FS_TYPES[$FS_TYPE]} /dev/mapper/$DEV_MAP ${A_OPTS_FSCK[$FS_TYPE]} && Notify || Exit; }	#FIXME: dosfsck fails on map
 
   LUKS_Mount
 
@@ -362,13 +376,21 @@ elif (($ACTION == 2)); then
   case "$FS_TYPE" in
     0) isoinfo -d -J -p -R -s -i /dev/mapper/$DEV_MAP;;
     1) dumpe2fs /dev/mapper/$DEV_MAP;;
+    3) swapon -s
   esac
 
 else
 
   Notify "Umount LUKS partition: " -n
-  umount /dev/mapper/$DEV_MAP && Notify || Exit
+  # since $FS_TYPE is undefined, detect swap type by another approach
+  if swapon -s | egrep -q "^/dev/mapper/$DEV_MAP[[:space:]]"; then
+    swapoff /dev/mapper/$DEV_MAP && Notify || Exit
+  else
+    umount /dev/mapper/$DEV_MAP && Notify || Exit
+  fi
   DEV_LOOP=$(cryptsetup status $DEV_MAP | egrep -o '/dev/loop[0-9]+')
   LUKS_Close
 
 fi
+
+exit 0
